// Fuente única de verdad del catálogo. Para agregar/editar un perfume,
// agrega o modifica un objeto aquí — el resto del sitio se genera solo.
//
// genero: "Masculino" | "Femenino" | "Unisex"
// tier:   "nicho" | "disenador"
// precios: deja "" en un valor si el decant aún no tiene precio (se verá vacío en la tarjeta)
// bestseller: true marca los perfumes que aparecen en el carrusel "Los más vendidos"

const PERFUMES = [
  // ---- NICHO ----
  {
    casa: "Xerjoff",
    nombre: "Erba Pura EDP",
    slug: "xerjoff-erba-pura",
    genero: "Unisex",
    tier: "nicho",
    imagen: "/imagenes/erba pura.webp",
    alt: "Erba Pura",
    notas: ["Naranja siciliana", "Bergamota", "Limón", "Vainilla", "Ámbar", "Almizcle blanco"],
    precios: { "3ml": "$280", "5ml": "$440", "10ml": "$844" },
    bestseller: false
  },
  {
    casa: "Le Labo",
    nombre: "Santal 33 EDP",
    slug: "le-labo-santal-33",
    genero: "Unisex",
    tier: "nicho",
    imagen: "/imagenes/santal 33.webp",
    alt: "Santal 33",
    notas: ["Cardamomo", "Iris", "Violeta", "Sándalo", "Cuero", "Almizcle", "Cedro"],
    precios: { "3ml": "$350", "5ml": "$554", "10ml": "$1,080" },
    bestseller: true
  },
  {
    casa: "Le Labo",
    nombre: "Another 13 EDP",
    slug: "le-labo-another-13",
    genero: "Unisex",
    tier: "nicho",
    imagen: "/imagenes/another 13.webp",
    alt: "Another 13",
    notas: ["Pera", "Manzana", "Cítricos", "Jazmín", "Musgo", "Ámbar gris", "Almizcle"],
    precios: { "3ml": "$350", "5ml": "$554", "10ml": "$1,080" },
    bestseller: false
  },
  {
    casa: "Francis Kurkdjian",
    nombre: "Baccarat Rouge 540 EDP",
    slug: "francis-kurkdjian-baccarat-rouge-540",
    genero: "Unisex",
    tier: "nicho",
    imagen: "/imagenes/baccarat rouge 540.webp",
    alt: "Baccarat Rouge 540",
    notas: ["Azafrán", "Jazmín", "Cedro ambarado", "Eritroxileno", "Almizcle"],
    precios: { "3ml": "$490", "5ml": "$790", "10ml": "$1,390" },
    bestseller: false
  },
  {
    casa: "Armani Privé",
    nombre: "Oud Royal EDP",
    slug: "armani-prive-oud-royal",
    genero: "Unisex",
    tier: "nicho",
    imagen: "/imagenes/oud royal.webp",
    alt: "Oud Royal",
    notas: ["Azafrán", "Incienso", "Rosa", "Ámbar", "Sándalo", "Oud"],
    precios: { "3ml": "$379", "5ml": "$607", "10ml": "$1,179" },
    bestseller: false
  },
  {
    casa: "Nasomatto",
    nombre: "Black Afgano Parfum",
    slug: "nasomatto-black-afgano",
    genero: "Unisex",
    tier: "nicho",
    imagen: "/imagenes/black afgano.webp",
    alt: "Black Afgano",
    notas: ["Cannabis", "Azafrán", "Tabaco", "Café", "Oud", "Incienso", "Ámbar", "Vainilla"],
    precios: { "3ml": "$570", "5ml": "$920", "10ml": "$1,800" },
    bestseller: false
  },
  {
    casa: "Le Labo",
    nombre: "Tonka 25 EDP",
    slug: "le-labo-tonka-25",
    genero: "Unisex",
    tier: "nicho",
    imagen: "/imagenes/tonka 25.webp",
    alt: "Tonka 25",
    notas: ["Flor de azahar", "Cedro", "Estoraque", "Haba tonka", "Almizcle", "Vainilla"],
    precios: { "3ml": "$350", "5ml": "$554", "10ml": "$1,080" },
    bestseller: false
  },
  {
    casa: "Kilian",
    nombre: "Black Phantom “Memento Mori” EDP",
    slug: "kilian-black-phantom-memento-mori",
    genero: "Unisex",
    tier: "nicho",
    imagen: "/imagenes/black phantom.webp",
    alt: "Black Phantom Memento Mori",
    notas: ["Ron", "Café", "Vetiver", "Ámbar", "Caña de azúcar", "Sándalo"],
    precios: { "3ml": "$542", "5ml": "$875", "10ml": "$1,708" },
    bestseller: false
  },

  // ---- DISEÑADOR ----
  {
    casa: "Maison Margiela",
    nombre: "Replica By the Fireplace EDT",
    slug: "maison-margiela-replica-by-the-fireplace",
    genero: "Unisex",
    tier: "disenador",
    imagen: "/imagenes/replica by the fireplace.webp",
    alt: "By the Fireplace",
    notas: ["Clavo", "Pimienta rosa", "Castaña", "Madera de guayaco", "Vainilla"],
    precios: { "3ml": "$140", "5ml": "$200", "10ml": "$360" },
    bestseller: false
  },
  {
    casa: "Louis Vuitton",
    nombre: "Imagination EDP",
    slug: "louis-vuitton-imagination",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/imagination.webp",
    alt: "Imagination",
    notas: ["Ambroxan", "Té negro", "Cedro", "Vainilla", "Iris"],
    precios: { "3ml": "$330", "5ml": "$530", "10ml": "$991" },
    bestseller: false
  },
  {
    casa: "Louis Vuitton",
    nombre: "L'Immensité EDP",
    slug: "louis-vuitton-limmensite",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/limmensité.webp",
    alt: "L'Immensité",
    notas: ["Jengibre", "Cardamomo", "Madera de haya", "Ambroxan", "Almizcle"],
    precios: { "3ml": "$330", "5ml": "$530", "10ml": "$991" },
    bestseller: false
  },
  {
    casa: "Dior",
    nombre: "Sauvage EDT",
    slug: "dior-sauvage",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/sauvage.webp",
    alt: "Sauvage",
    notas: ["Bergamota", "Pimienta", "Lavanda", "Ambroxan", "Cedro", "Patchouli"],
    precios: { "3ml": "$140", "5ml": "$240", "10ml": "$440" },
    bestseller: false
  },
  {
    casa: "Chanel",
    nombre: "Bleu de Chanel EDP",
    slug: "chanel-bleu-de-chanel",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/bleu de chanel.webp",
    alt: "Bleu de Chanel",
    notas: ["Limón", "Menta", "Jengibre", "Jazmín", "Incienso", "Sándalo", "Cedro"],
    precios: { "3ml": "$225", "5ml": "$350", "10ml": "$650" },
    bestseller: false
  },
  {
    casa: "YSL",
    nombre: "Libre EDP",
    slug: "ysl-libre",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/libre.webp",
    alt: "Libre",
    notas: ["Lavanda", "Mandarina", "Vainilla", "Almizcle blanco", "Cedro"],
    precios: { "3ml": "$176", "5ml": "$266", "10ml": "$495" },
    bestseller: false
  },
  {
    casa: "Valentino",
    nombre: "Uomo Born in Roma Intense EDP",
    slug: "valentino-uomo-born-in-roma-intense",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/born in roma intense.webp",
    alt: "Born in Roma Intense",
    notas: ["Vainilla bourbon", "Lavanda", "Vetiver", "Madera ambarada"],
    precios: { "3ml": "$220", "5ml": "$374", "10ml": "$707" },
    bestseller: true
  },
  {
    casa: "Chanel",
    nombre: "Chance Eau Tendre EDP",
    slug: "chanel-chance-eau-tendre",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/chance eau tendre.webp",
    alt: "Chance Eau Tendre",
    notas: ["Pomelo", "Jacinto", "Jazmín", "Almizcle blanco", "Cedro"],
    precios: { "3ml": "$245", "5ml": "$375", "10ml": "$700" },
    bestseller: true
  },
  {
    casa: "Prada",
    nombre: "Paradoxe Intense EDP",
    slug: "prada-paradoxe-intense",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/paradoxe.webp",
    alt: "Paradoxe",
    notas: ["Neroli", "Flor de azahar", "Almizcle blanco", "Sándalo", "Ámbar"],
    precios: { "3ml": "$170", "5ml": "$250", "10ml": "$458" },
    bestseller: true
  },
  {
    casa: "Valentino",
    nombre: "Donna Born in Roma Intense EDP",
    slug: "valentino-donna-born-in-roma-intense",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/born in roma intense donna.webp",
    alt: "Donna Born in Roma Intense",
    notas: ["Bergamota", "Jazmín sambac", "Iris blanco", "Vainilla bourbon", "Almizcle"],
    precios: { "3ml": "$155", "5ml": "$230", "10ml": "$410" },
    bestseller: true
  },
  {
    casa: "YSL",
    nombre: "Y EDP",
    slug: "ysl-y",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/y edp.webp",
    alt: "Y EDP",
    notas: ["Manzana", "Jengibre", "Bergamota", "Salvia", "Haba tonka", "Cedro"],
    precios: { "3ml": "$150", "5ml": "$220", "10ml": "$395" },
    bestseller: false
  },
  {
    casa: "Armani",
    nombre: "Acqua di Gio Profondo EDP",
    slug: "armani-acqua-di-gio-profondo",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/acqua di gio profondo.webp",
    alt: "Acqua di Gio",
    notas: ["Bergamota", "Menta acuática", "Lavanda marina", "Patchouli", "Almizcle"],
    precios: { "3ml": "$140", "5ml": "$210", "10ml": "$361" },
    bestseller: false
  },
  {
    casa: "Lancôme",
    nombre: "La Vie Est Belle EDP",
    slug: "lancome-la-vie-est-belle",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/la vie est belle.webp",
    alt: "La Vie Est Belle",
    notas: ["Iris", "Jazmín", "Praline", "Vainilla", "Patchouli", "Gourmand"],
    precios: { "3ml": "$150", "5ml": "$220", "10ml": "$386" },
    bestseller: false
  },
  {
    casa: "Paco Rabanne",
    nombre: "1 Million EDT",
    slug: "paco-rabanne-1-million",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/1 million.webp",
    alt: "1 Million",
    notas: ["Menta", "Pomelo", "Rosa", "Canela", "Cuero", "Ámbar", "Patchouli"],
    precios: { "3ml": "$145", "5ml": "$210", "10ml": "$375" },
    bestseller: false
  },
  {
    casa: "Paco Rabanne",
    nombre: "Olympéa EDP",
    slug: "paco-rabanne-olympea",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/olympea.webp",
    alt: "Olympéa",
    notas: ["Flor de té verde", "Sal marina", "Pimienta blanca", "Vainilla", "Cachemir"],
    precios: { "3ml": "$130", "5ml": "$185", "10ml": "$324" },
    bestseller: false
  },
  {
    casa: "Guerlain",
    nombre: "Mon Guerlain EDP",
    slug: "guerlain-mon-guerlain",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/mon guerlain.webp",
    alt: "Mon Guerlain",
    notas: ["Lavanda", "Bergamota", "Iris", "Jazmín sambac", "Rosa", "Vainilla", "Sándalo"],
    precios: { "3ml": "$130", "5ml": "$185", "10ml": "$330" },
    bestseller: false
  },
  {
    casa: "Dolce & Gabbana",
    nombre: "Light Blue EDT",
    slug: "dolce-gabbana-light-blue-decant",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/light blue.webp",
    alt: "Light Blue",
    notas: ["Limón siciliano", "Manzana verde", "Campanilla", "Rosa blanca", "Bambú", "Ámbar", "Almizcle"],
    precios: { "3ml": "$92", "5ml": "$130", "10ml": "$210" },
    bestseller: false
  },
  {
    casa: "Calvin Klein",
    nombre: "CK One EDT",
    slug: "calvin-klein-ck-one",
    genero: "Unisex",
    tier: "disenador",
    imagen: "/imagenes/ck one.webp",
    alt: "CK One",
    notas: ["Limón", "Bergamota", "Piña", "Muguete", "Jazmín", "Violeta", "Almizcle", "Cedro", "Ámbar"],
    precios: { "3ml": "$57", "5ml": "$67", "10ml": "$92" },
    bestseller: false
  },
  {
    casa: "Lacoste",
    nombre: "Red EDT",
    slug: "lacoste-red",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/lacoste red.webp",
    alt: "Lacoste Red",
    notas: ["Manzana", "Cedro", "Pino", "Jazmín", "Patchouli", "Vetiver"],
    precios: { "3ml": "$94", "5ml": "$129", "10ml": "$217" },
    bestseller: false
  },
  {
    casa: "Dolce & Gabbana",
    nombre: "Light Blue Pour Homme EDT",
    slug: "dolce-gabbana-light-blue-pour-homme",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/light blue pour homme.webp",
    alt: "Light Blue Pour Homme",
    notas: ["Limón", "Romero", "Pachulí"],
    precios: { "3ml": "$92", "5ml": "$130", "10ml": "$210" },
    bestseller: false
  },
  {
    casa: "Jean Paul Gaultier",
    nombre: "Le Beau Le Parfum EDP",
    slug: "jean-paul-gaultier-le-beau-le-parfum",
    genero: "Masculino",
    tier: "disenador",
    imagen: "/imagenes/le beau le parfum.webp",
    alt: "Le Beau Le Parfum",
    notas: ["Piña", "Iris", "Jengibre", "Coco", "Haba tonka", "Sándalo", "Ámbar"],
    precios: { "3ml": "$120", "5ml": "$170", "10ml": "$295" },
    bestseller: false
  },
  {
    casa: "Carolina Herrera",
    nombre: "Good Girl Blush EDP",
    slug: "carolina-herrera-good-girl-blush",
    genero: "Femenino",
    tier: "disenador",
    imagen: "/imagenes/good girl blush.webp",
    alt: "Good Girl Blush",
    notas: ["Lychee", "Pimienta rosa", "Peonía", "Rosa", "Sándalo", "Almizcle blanco"],
    precios: { "3ml": "$170", "5ml": "$255", "10ml": "$466" },
    bestseller: false
  }
];

// Perfumes de línea completa (no decants): sin precio ni tamaños, se cotizan
// por WhatsApp. Fotos pendientes de agregar en imagenes/completos/<archivo>.
const PERFUMES_COMPLETOS = [
  // ---- CABALLERO ----
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Invictus", slug: "paco-rabanne-invictus", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/invictus.webp", alt: "Invictus", precio: "$1,950" },
  { casa: "Azzaro", categoria: "disenador", nombre: "The Most Wanted", slug: "azzaro-the-most-wanted", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/the_most_wanted.webp", alt: "The Most Wanted", precio: "$1,630" },
  { casa: "Dolce & Gabbana", categoria: "disenador", nombre: "King", slug: "dolce-gabbana-king", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/king.webp", alt: "King", precio: "$1,940" },
  { casa: "Dior", categoria: "disenador", nombre: "Sauvage", slug: "dior-sauvage-parfum", tamano: "100ml", concentracion: "Parfum", genero: "Caballero", imagen: "/imagenes/completos/sauvage_parfum.webp", alt: "Sauvage Parfum", precio: "$3,950" },
  { casa: "Valentino", categoria: "disenador", nombre: "Uomo Born In Roma Intense", slug: "valentino-uomo-born-in-roma-intense-completo", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/uomo_born_in_roma_intense.webp", alt: "Uomo Born In Roma Intense", precio: "$3,450" },
  { casa: "Valentino", categoria: "disenador", nombre: "Uomo Born In Roma Yellow Dream", slug: "valentino-uomo-born-in-roma-yellow-dream", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/uomo_born_in_roma_yellow_dream.webp", alt: "Uomo Born In Roma Yellow Dream", precio: "$2,649" },
  { casa: "Valentino", categoria: "disenador", nombre: "Uomo Born In Roma Green Stravaganza", slug: "valentino-uomo-born-in-roma-green-stravaganza", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/uomo_born_in_roma_green_stravaganza.webp", alt: "Uomo Born In Roma Green Stravaganza", precio: "$2,800" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Male Elixir", slug: "jean-paul-gaultier-le-male-elixir", tamano: "125ml", concentracion: "Parfum", genero: "Caballero", imagen: "/imagenes/completos/le_male_elixir.webp", alt: "Le Male Elixir", precio: "$2,422" },
  { casa: "Dior", categoria: "disenador", nombre: "Sauvage", slug: "dior-sauvage-edp", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/sauvage_edp.webp", alt: "Sauvage EDP", precio: "$3,494" },
  { casa: "Lacoste", categoria: "disenador", nombre: "Blanc", slug: "lacoste-blanc", tamano: "175ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/blanc.webp", alt: "Blanc", precio: "$1,890" },
  { casa: "Versace", categoria: "disenador", nombre: "Pour Homme Dylan Blue", slug: "versace-pour-homme-dylan-blue", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/dylan_blue.webp", alt: "Pour Homme Dylan Blue", precio: "$1,990" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "One Million Parfum", slug: "paco-rabanne-one-million-parfum", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/one_million_parfum.webp", alt: "One Million Parfum", precio: "$2,580" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "One Million", slug: "paco-rabanne-one-million", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/one_million_edt.webp", alt: "One Million", precio: "$2,100" },
  { casa: "Montblanc", categoria: "disenador", nombre: "Explorer", slug: "montblanc-explorer", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/explorer.webp", alt: "Explorer", precio: "$1,950" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Beau Le Parfum", slug: "jean-paul-gaultier-le-beau-le-parfum", tamano: "125ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/le_beau_le_parfum.webp", alt: "Le Beau Le Parfum", precio: "$2,699" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Beau", slug: "jean-paul-gaultier-le-beau", tamano: "125ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/le_beau_edt.webp", alt: "Le Beau", precio: "$2,299" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Male", slug: "jean-paul-gaultier-le-male", tamano: "125ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/le_male_edt.webp", alt: "Le Male", precio: "$2,199" },
  { casa: "Versace", categoria: "disenador", nombre: "Eros", slug: "versace-eros-edt", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/eros_edt.webp", alt: "Eros EDT", precio: "$1,999" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Bad Boy Elixir", slug: "carolina-herrera-bad-boy-elixir", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/bad_boy_elixir.webp", alt: "Bad Boy Elixir", precio: "$2,690" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Bad Boy Cobalt Elixir", slug: "carolina-herrera-bad-boy-cobalt-elixir", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/bad_boy_cobalt_elixir.webp", alt: "Bad Boy Cobalt Elixir", precio: "$2,690" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Bad Boy Cobalt", slug: "carolina-herrera-bad-boy-cobalt", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/bad_boy_cobalt.webp", alt: "Bad Boy Cobalt", precio: "$2,290" },
  { casa: "Versace", categoria: "disenador", nombre: "Eros", slug: "versace-eros-edp", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/eros_edp.webp", alt: "Eros EDP", precio: "$2,490" },
  { casa: "Guerlain", categoria: "disenador", nombre: "Vetiver", slug: "guerlain-vetiver", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/vetiver.webp", alt: "Vetiver", precio: "$2,150" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Bad Boy", slug: "carolina-herrera-bad-boy", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/bad_boy.webp", alt: "Bad Boy", precio: "$2,100" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Invictus Victory", slug: "paco-rabanne-invictus-victory", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/invictus_victory.webp", alt: "Invictus Victory", precio: "$2,560" },
  { casa: "Dolce & Gabbana", categoria: "disenador", nombre: "Light Blue Pour Homme", slug: "dolce-gabbana-light-blue-pour-homme", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/light_blue_pour_homme.webp", alt: "Light Blue Pour Homme", precio: "$1,980" },
  { casa: "Dolce & Gabbana", categoria: "disenador", nombre: "Light Blue Capri In Love Pour Homme", slug: "dolce-gabbana-light-blue-capri-in-love-pour-homme", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/light_blue_capri_in_love_pour_homme.webp", alt: "Light Blue Capri In Love Pour Homme", precio: "$1,980" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Scandal Intense", slug: "jean-paul-gaultier-scandal-pour-homme-intense", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/scandal_intense.webp", alt: "Scandal Intense", precio: "$2,590" },
  { casa: "Giorgio Armani", categoria: "disenador", nombre: "Acqua Di Gio", slug: "armani-acqua-di-gio", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/acqua_di_gio.webp", alt: "Acqua Di Gio", precio: "$2,100" },
  { casa: "Giorgio Armani", categoria: "disenador", nombre: "Stronger With You", slug: "armani-stronger-with-you", tamano: "100ml", concentracion: "Parfum", genero: "Caballero", imagen: "/imagenes/completos/stronger_with_you.webp", alt: "Stronger With You", precio: "$2,275" },
  { casa: "Valentino", categoria: "disenador", nombre: "Uomo Born In Roma Coral Fantasy", slug: "valentino-uomo-born-in-roma-coral-fantasy", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/uomo_born_in_roma_coral_fantasy.webp", alt: "Uomo Born In Roma Coral Fantasy", precio: "$2,800" },
  { casa: "Valentino", categoria: "disenador", nombre: "Uomo", slug: "valentino-uomo", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/uomo.webp", alt: "Uomo", precio: "$2,580" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Scandal", slug: "jean-paul-gaultier-scandal-pour-homme-edp", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/scandal_edp.webp", alt: "Scandal EDP", precio: "$2,375" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Scandal", slug: "jean-paul-gaultier-scandal-pour-homme-edt", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/scandal_edt.webp", alt: "Scandal EDT", precio: "$2,199" },
  { casa: "Givenchy", categoria: "disenador", nombre: "Pi", slug: "givenchy-pi", tamano: "100ml", concentracion: "EDT", genero: "Caballero", imagen: "/imagenes/completos/givenchy_pi.webp", alt: "Givenchy Pi", precio: "$1,380" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Beau Paradise Garden", slug: "jean-paul-gaultier-le-beau-paradise-garden", tamano: "125ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/le_beau_paradise_garden.webp", alt: "Le Beau Paradise Garden", precio: "$2,699" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Invictus Parfum", slug: "paco-rabanne-invictus-parfum", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/invictus_parfum.webp", alt: "Invictus Parfum", precio: "$2,549" },
  { casa: "YSL", categoria: "disenador", nombre: "Y Intense", slug: "ysl-y-intense", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/y_intense.webp", alt: "Y Intense", precio: "$2,990" },
  { casa: "YSL", categoria: "disenador", nombre: "Y", slug: "ysl-y-completo", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/y_edp.webp", alt: "Y", precio: "$2,950" },

  // ---- DAMA ----
  { casa: "Dolce & Gabbana", categoria: "disenador", nombre: "Queen", slug: "dolce-gabbana-queen", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/queen.webp", alt: "Queen", precio: "$2,450" },
  { casa: "Dolce & Gabbana", categoria: "disenador", nombre: "Light Blue Summer Vibes", slug: "dolce-gabbana-light-blue-summer-vibes", tamano: "100ml", concentracion: "EDT", genero: "Dama", imagen: "/imagenes/completos/light_blue_summer_vibes.webp", alt: "Light Blue Summer Vibes", precio: "$1,850" },
  { casa: "YSL", categoria: "disenador", nombre: "Libre L'Eau Nue Parfum de Peau", slug: "ysl-libre-eau-nue", tamano: "90ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/libre_leau_nue_parfum_de_peau.webp", alt: "Libre L'Eau Nue Parfum de Peau", precio: "$2,549" },
  { casa: "Burberry", categoria: "disenador", nombre: "My Burberry Blush", slug: "burberry-my-burberry-blush", tamano: "90ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/my_burberry_blush.webp", alt: "My Burberry Blush", precio: "$2,450" },
  { casa: "Prada", categoria: "disenador", nombre: "Paradoxe Virtual Flower", slug: "prada-paradoxe-virtual-flower", tamano: "90ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/paradoxe_virtual_flower.webp", alt: "Paradoxe Virtual Flower", precio: "$2,995" },
  { casa: "Prada", categoria: "disenador", nombre: "Paradoxe Intense", slug: "prada-paradoxe-intense-completo", tamano: "90ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/paradoxe_intense.webp", alt: "Paradoxe Intense", precio: "$2,950" },
  { casa: "Dior", categoria: "disenador", nombre: "J'adore Parfum d'Eau", slug: "dior-jadore-parfum-deau", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/jadore_parfum_deau.webp", alt: "J'adore Parfum d'Eau", precio: "$3,300" },
  { casa: "Adolfo Domínguez", categoria: "disenador", nombre: "Jazmín Tonka", slug: "adolfo-dominguez-jazmin-tonka", tamano: "120ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/jazmin_tonka.webp", alt: "Jazmín Tonka", precio: "$1,500" },
  { casa: "Salvatore Ferragamo", categoria: "disenador", nombre: "Signorina Unica", slug: "salvatore-ferragamo-signorina-unica", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/signorina_unica.webp", alt: "Signorina Unica", precio: "$2,100" },
  { casa: "Salvatore Ferragamo", categoria: "disenador", nombre: "Signorina Libera", slug: "salvatore-ferragamo-signorina-libera", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/signorina_libera.webp", alt: "Signorina Libera", precio: "$2,050" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Very Good Girl Elixir", slug: "carolina-herrera-very-good-girl-elixir", tamano: "80ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/very_good_girl_elixir.webp", alt: "Very Good Girl Elixir", precio: "$2,990" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Good Girl Blush Elixir", slug: "carolina-herrera-good-girl-blush-elixir", tamano: "80ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/good_girl_blush_elixir.webp", alt: "Good Girl Blush Elixir", precio: "$2,990" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Good Girl Blush", slug: "carolina-herrera-good-girl-blush", tamano: "80ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/good_girl_blush.webp", alt: "Good Girl Blush", precio: "$2,920" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Very Good Girl", slug: "carolina-herrera-very-good-girl", tamano: "80ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/very_good_girl.webp", alt: "Very Good Girl", precio: "$2,920" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Good Girl", slug: "carolina-herrera-good-girl", tamano: "80ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/good_girl.webp", alt: "Good Girl", precio: "$2,850" },
  { casa: "Valentino", categoria: "disenador", nombre: "Donna Born In Roma Yellow Dream", slug: "valentino-donna-born-in-roma-yellow-dream", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/donna_born_in_roma_yellow_dream.webp", alt: "Donna Born In Roma Yellow Dream", precio: "$2,950" },
  { casa: "Lancôme", categoria: "disenador", nombre: "La Vie Est Belle", slug: "lancome-la-vie-est-belle", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/la_vie_est_belle.webp", alt: "La Vie Est Belle", precio: "$2,850" },
  { casa: "Lancôme", categoria: "disenador", nombre: "La Vie Est Belle Iris Absolu", slug: "lancome-la-vie-est-belle-iris-absolu", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/la_vie_est_belle_iris_absolu.webp", alt: "La Vie Est Belle Iris Absolu", precio: "$2,850" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Olympéa", slug: "paco-rabanne-olympea", tamano: "80ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/olympea.webp", alt: "Olympéa", precio: "$2,500" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Lady Million", slug: "paco-rabanne-lady-million", tamano: "80ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/lady_million.webp", alt: "Lady Million", precio: "$2,500" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Olympéa Parfum", slug: "paco-rabanne-olympea-parfum", tamano: "80ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/olympea_parfum.webp", alt: "Olympéa Parfum", precio: "$2,700" },
  { casa: "Tom Ford", categoria: "disenador", nombre: "Black Orchid", slug: "tom-ford-black-orchid", tamano: "100ml", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/black_orchid.webp", alt: "Black Orchid", precio: "$3,200" },
  { casa: "Tom Ford", categoria: "disenador", nombre: "Velvet Orchid", slug: "tom-ford-velvet-orchid", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/velvet_orchid.webp", alt: "Velvet Orchid", precio: "$3,200" },
  { casa: "Coach", categoria: "disenador", nombre: "Coach New York", slug: "coach-new-york", tamano: "90ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/coach_new_york.webp", alt: "Coach New York", precio: "$1,760" },
  { casa: "DKNY", categoria: "disenador", nombre: "Be Delicious", slug: "dkny-be-delicious", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/be_delicious.webp", alt: "Be Delicious", precio: "$1,500" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "La Belle Paradise Garden", slug: "jean-paul-gaultier-la-belle-paradise-garden", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/la_belle_paradise_garden.webp", alt: "La Belle Paradise Garden", precio: "$2,880" },
  { casa: "Dolce & Gabbana", categoria: "disenador", nombre: "The Only One Intense", slug: "dolce-gabbana-the-only-one-intense", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/the_only_one_intense.webp", alt: "The Only One Intense", precio: "$1,890" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Divine", slug: "jean-paul-gaultier-divine", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/divine.webp", alt: "Divine", precio: "$2,650" },
  { casa: "Billie Eilish", categoria: "disenador", nombre: "Billie Eilish", slug: "billie-eilish", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/billie_eilish.webp", alt: "Billie Eilish", precio: "$1,480" },
  { casa: "Moschino", categoria: "disenador", nombre: "Fresh Couture Gold", slug: "moschino-fresh-couture-gold", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/fresh_couture_gold.webp", alt: "Fresh Couture Gold", precio: "$1,850" },
  { casa: "Moschino", categoria: "disenador", nombre: "Fresh Couture", slug: "moschino-fresh-couture", tamano: "100ml", concentracion: "EDT", genero: "Dama", imagen: "/imagenes/completos/fresh_couture.webp", alt: "Fresh Couture", precio: "$1,850" },
  { casa: "Versace", categoria: "disenador", nombre: "Pour Femme Dylan Blue", slug: "versace-pour-femme-dylan-blue", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/dylan_blue_femme.webp", alt: "Pour Femme Dylan Blue", precio: "$1,990" },
  { casa: "Valentino", categoria: "disenador", nombre: "Donna", slug: "valentino-donna", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/donna.webp", alt: "Donna", precio: "$2,950" },
  { casa: "YSL", categoria: "disenador", nombre: "Mon Paris Intensement", slug: "ysl-mon-paris-intensement", tamano: "90ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/mon_paris_intensement.webp", alt: "Mon Paris Intensement", precio: "$2,990" },
  { casa: "Moschino", categoria: "disenador", nombre: "Fresh Couture Pink", slug: "moschino-fresh-couture-pink", tamano: "100ml", concentracion: "EDT", genero: "Dama", imagen: "/imagenes/completos/fresh_couture_pink.webp", alt: "Fresh Couture Pink", precio: "$1,850" },
  { casa: "Dolce & Gabbana", categoria: "disenador", nombre: "Light Blue", slug: "dolce-gabbana-light-blue", tamano: "100ml", concentracion: "EDT", genero: "Dama", imagen: "/imagenes/completos/light_blue.webp", alt: "Light Blue", precio: "$1,764" },
  { casa: "Dior", categoria: "disenador", nombre: "Miss Dior", slug: "dior-miss-dior", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/miss_dior.webp", alt: "Miss Dior", precio: "$3,349" },
  { casa: "Burberry", categoria: "disenador", nombre: "Her", slug: "burberry-her", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/burberry_her.webp", alt: "Burberry Her", precio: "$3,349" },
  { casa: "Dolce & Gabbana", categoria: "disenador", nombre: "Light Blue Capri In Love", slug: "dolce-gabbana-light-blue-capri-in-love", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/light_blue_capri_in_love.webp", alt: "Light Blue Capri In Love", precio: "$1,980" },
  { casa: "YSL", categoria: "disenador", nombre: "Libre", slug: "ysl-libre", tamano: "90ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/libre.webp", alt: "Libre", precio: "$2,950" },
  { casa: "Dior", categoria: "disenador", nombre: "Miss Dior Originale", slug: "dior-miss-dior-originale", tamano: "100ml", concentracion: "EDT", genero: "Dama", imagen: "/imagenes/completos/miss_dior_originale.webp", alt: "Miss Dior Originale", precio: "$2,750" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Bad Boy Cobalt Absolute", slug: "carolina-herrera-bad-boy-cobalt-absolute", tamano: "100ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/bad_boy_cobalt_absolute.webp", alt: "Bad Boy Cobalt Absolute", precio: "$2,500" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Beau Narcisse", slug: "jean-paul-gaultier-le-beau-narcisse", tamano: "125ml", concentracion: "EDP", genero: "Caballero", imagen: "/imagenes/completos/le_beau_narcisse.webp", alt: "Le Beau Narcisse", precio: "$2,550" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Male Elixir Absolu", slug: "jean-paul-gaultier-le-male-elixir-absolu", tamano: "125ml", concentracion: "Parfum", genero: "Caballero", imagen: "/imagenes/completos/le_male_elixir_absolu.webp", alt: "Le Male Elixir Absolu", precio: "$2,700" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "La Belle Rosea", slug: "jean-paul-gaultier-la-belle-rosea", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/la_belle_rosea.webp", alt: "La Belle Rosea", precio: "$2,800" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "CH Swing", slug: "carolina-herrera-ch-swing", tamano: "100ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/ch_swing.webp", alt: "CH Swing", precio: "$2,500" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Million Gold For Her Pure Diamonds", slug: "paco-rabanne-million-gold-pure-diamonds", tamano: "90ml", concentracion: "EDP", genero: "Dama", imagen: "/imagenes/completos/million_gold_pure_diamonds.webp", alt: "Million Gold For Her Pure Diamonds", precio: "$2,550" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Million Gold For Her", slug: "paco-rabanne-million-gold-parfum", tamano: "90ml", concentracion: "Parfum", genero: "Dama", imagen: "/imagenes/completos/million_gold_parfum.webp", alt: "Million Gold For Her Parfum", precio: "$2,600" },

  // ---- NICHO (sin precio fijo — disponibilidad sujeta a proveedor) ----
  { casa: "Xerjoff", categoria: "nicho", nombre: "Erba Pura", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/erba_pura.webp", alt: "Erba Pura", precio: null },
  { casa: "Xerjoff", categoria: "nicho", nombre: "Naxos", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/naxos.webp", alt: "Naxos", precio: null },
  { casa: "Xerjoff", categoria: "nicho", nombre: "Torino 21", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/torino_21.webp", alt: "Torino 21", precio: null },
  { casa: "Parfums De Marly", categoria: "nicho", nombre: "Althair", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/althair.webp", alt: "Althair", precio: null },
  { casa: "Parfums De Marly", categoria: "nicho", nombre: "Greenley", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/greenley.webp", alt: "Greenley", precio: null },
  { casa: "Parfums De Marly", categoria: "nicho", nombre: "Percival", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/percival.webp", alt: "Percival", precio: null },
  { casa: "Parfums De Marly", categoria: "nicho", nombre: "Layton", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/layton.webp", alt: "Layton", precio: null },
  { casa: "Parfums De Marly", categoria: "nicho", nombre: "Castley", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/castley.webp", alt: "Castley", precio: null },
  { casa: "Mancera", categoria: "nicho", nombre: "Instant Crush", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/instant_crush.webp", alt: "Instant Crush", precio: null },
  { casa: "Mancera", categoria: "nicho", nombre: "Cedrat Boisé", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/cedrat_boise.webp", alt: "Cedrat Boisé", precio: null },
  { casa: "Francis Kurkdjian", categoria: "nicho", nombre: "Baccarat Rouge 540", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/baccarat_rouge_540.webp", alt: "Baccarat Rouge 540", precio: null },
  { casa: "Le Labo", categoria: "nicho", nombre: "Santal 33", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/santal_33.webp", alt: "Santal 33", precio: null },
  { casa: "Le Labo", categoria: "nicho", nombre: "Thé Noir 29", concentracion: "EDP", genero: "Unisex", imagen: "/imagenes/completos/the_noir_29.webp", alt: "Thé Noir 29", precio: null },

  // ---- SETS DE REGALO ----
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Lady Million Estuche 2 Piezas", slug: "paco-rabanne-lady-million-estuche", tamano: "80ml", concentracion: "EDP", genero: "Dama", esSet: true, contenido: ["EDP 80ml", "Loción corporal 100ml"], imagen: "/imagenes/completos/lady_million_estuche.webp", alt: "Lady Million Estuche 2 Piezas", precio: "$2,800" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Olympéa Estuche 2 Piezas", slug: "paco-rabanne-olympea-estuche", tamano: "80ml", concentracion: "EDP", genero: "Dama", esSet: true, contenido: ["EDP 80ml", "Loción corporal 100ml"], imagen: "/imagenes/completos/olympea_estuche.webp", alt: "Olympéa Estuche 2 Piezas", precio: "$2,700" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Million Gold For Her Estuche 3 Piezas", slug: "paco-rabanne-million-gold-for-her-estuche", tamano: "90ml", concentracion: "EDP", genero: "Dama", esSet: true, contenido: ["EDP 90ml", "Loción corporal 100ml", "Miniatura 5ml"], imagen: "/imagenes/completos/million_gold_for_her_estuche.webp", alt: "Million Gold For Her Estuche 3 Piezas", precio: "$2,800" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Very Good Girl Elixir Estuche 3 Piezas", slug: "carolina-herrera-very-good-girl-elixir-estuche", tamano: "80ml", concentracion: "EDP", genero: "Dama", esSet: true, contenido: ["EDP 80ml", "Loción corporal 100ml", "Miniatura 10ml"], imagen: "/imagenes/completos/very_good_girl_elixir_estuche.webp", alt: "Very Good Girl Elixir Estuche 3 Piezas", precio: "$3,250" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Very Good Girl Estuche 3 Piezas", slug: "carolina-herrera-very-good-girl-estuche", tamano: "80ml", concentracion: "EDP", genero: "Dama", esSet: true, contenido: ["EDP 80ml", "Loción corporal 100ml", "Miniatura 10ml"], imagen: "/imagenes/completos/very_good_girl_estuche.webp", alt: "Very Good Girl Estuche 3 Piezas", precio: "$3,250" },
  { casa: "Salvatore Ferragamo", categoria: "disenador", nombre: "Signorina Estuche 3 Piezas", slug: "salvatore-ferragamo-signorina-estuche", tamano: "100ml", concentracion: "EDP", genero: "Dama", esSet: true, contenido: ["EDP 100ml", "Loción corporal 50ml", "Miniatura 15ml"], imagen: "/imagenes/completos/signorina_estuche.webp", alt: "Signorina Estuche 3 Piezas", precio: "$2,300" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Good Girl Estuche 3 Piezas", slug: "carolina-herrera-good-girl-estuche", tamano: "80ml", concentracion: "EDP", genero: "Dama", esSet: true, contenido: ["EDP 80ml", "Loción corporal 100ml", "Miniatura 10ml"], imagen: "/imagenes/completos/good_girl_estuche.webp", alt: "Good Girl Estuche 3 Piezas", precio: "$3,150" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Beau Estuche 2 Piezas", slug: "jean-paul-gaultier-le-beau-estuche", tamano: "125ml", concentracion: "EDT", genero: "Caballero", esSet: true, contenido: ["EDT 125ml", "Miniatura 10ml"], imagen: "/imagenes/completos/le_beau_estuche.webp", alt: "Le Beau Estuche 2 Piezas", precio: "$2,499" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "One Million Estuche 3 Piezas", slug: "paco-rabanne-one-million-estuche", tamano: "100ml", concentracion: "EDT", genero: "Caballero", esSet: true, contenido: ["EDT 100ml", "Desodorante 150ml", "Miniatura 10ml"], imagen: "/imagenes/completos/one_million_estuche.webp", alt: "One Million Estuche 3 Piezas", precio: "$2,350" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Invictus Victory Estuche 2 Piezas", slug: "paco-rabanne-invictus-victory-estuche", tamano: "100ml", concentracion: "EDP", genero: "Caballero", esSet: true, contenido: ["EDP 100ml", "Shampoo 100ml"], imagen: "/imagenes/completos/invictus_victory_estuche.webp", alt: "Invictus Victory Estuche 2 Piezas", precio: "$2,750" },
  { casa: "Jean Paul Gaultier", categoria: "disenador", nombre: "Le Male Estuche 3 Piezas", slug: "jean-paul-gaultier-le-male-estuche", tamano: "125ml", concentracion: "EDT", genero: "Caballero", esSet: true, contenido: ["EDT 125ml", "Desodorante 150ml", "Gel de baño 75ml"], imagen: "/imagenes/completos/le_male_estuche.webp", alt: "Le Male Estuche 3 Piezas", precio: "$2,450" },
  { casa: "Paco Rabanne", categoria: "disenador", nombre: "Invictus Estuche 3 Piezas", slug: "paco-rabanne-invictus-estuche", tamano: "100ml", concentracion: "EDT", genero: "Caballero", esSet: true, contenido: ["EDT 100ml", "Desodorante 150ml", "Miniatura 10ml"], imagen: "/imagenes/completos/invictus_estuche.webp", alt: "Invictus Estuche 3 Piezas", precio: "$2,250" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Bad Boy Elixir Estuche 3 Piezas", slug: "carolina-herrera-bad-boy-elixir-estuche", tamano: "100ml", concentracion: "EDP", genero: "Caballero", esSet: true, contenido: ["EDP 100ml", "Gel de baño 100ml", "Miniatura 10ml"], imagen: "/imagenes/completos/bad_boy_elixir_estuche.webp", alt: "Bad Boy Elixir Estuche 3 Piezas", precio: "$2,450" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Bad Boy Cobalt Estuche 3 Piezas", slug: "carolina-herrera-bad-boy-cobalt-estuche", tamano: "100ml", concentracion: "EDP", genero: "Caballero", esSet: true, contenido: ["EDP 100ml", "Gel de baño 100ml", "Miniatura 10ml"], imagen: "/imagenes/completos/bad_boy_cobalt_estuche.webp", alt: "Bad Boy Cobalt Estuche 3 Piezas", precio: "$2,550" },
  { casa: "Carolina Herrera", categoria: "disenador", nombre: "Bad Boy Estuche 3 Piezas", slug: "carolina-herrera-bad-boy-estuche", tamano: "100ml", concentracion: "EDT", genero: "Caballero", esSet: true, contenido: ["EDT 100ml", "Gel de baño 100ml", "Miniatura 10ml"], imagen: "/imagenes/completos/bad_boy_estuche.webp", alt: "Bad Boy Estuche 3 Piezas", precio: "$2,450" }
];
